wmcontent.wmcontent_container.*:
  type: config_entity
  label: 'WmContent Container'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    host_entity_type:
      type: string
      label: 'Host entity type'
    host_bundles:
      type: sequence
      label: 'Host bundles'
      sequence:
        type: string
    child_entity_type:
      type: string
      label: 'Child entity type'
    child_bundles:
      type: sequence
      label: 'Child bundles'
      sequence:
        type: string
    child_bundles_default:
      type: string
      label: 'Default child bundle'
      sequence:
        type: string
    hide_single_option_sizes:
      type: boolean
      label: 'Hide single option sizes'
    hide_single_option_alignments:
      type: boolean
      label: 'Hide single option alignments'
    show_size_column:
      type: boolean
      label: 'Show size column'
    show_alignment_column:
      type: boolean
      label: 'Show alignment column'
    snapshots_enabled:
      type: boolean
      label: 'Enable snapshots'
